language: java

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - mysql
before_install:
  - mysql -e 'DROP DATABASE IF EXISTS market;'
  - mysql -e 'CREATE DATABASE market;'

script: mvn test -Dspring.profiles.active=mysql