language: java

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - mysql

before_script:
  - echo -e "[mysqld]\nlower_case_table_names = 1" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart

before_install:
  - mysql --verbose -e  "show variables like 'lower%';"
  - mysql -e 'DROP DATABASE IF EXISTS market;'
  - mysql -e 'CREATE DATABASE market;'

script: mvn test -Dspring.profiles.active=mysql